# Go to the following URL for a list of available OpenShift versions for installation
# https://mirror.openshift.com/pub/openshift-v4/clients/ocp/

# get installation files playbook variables
openshift_version:                      4.4.8
openshift_installer_path:               "{{ ansible_env.PWD }}"
openshift_odo_version:                  1.2.1
openshift_odo_path:                     /usr/local/bin/

# openshift workshop user variables
openshift_cluster_admin_username:       labadmin
openshift_cluster_admin_password:       labadmin#01
openshift_user_count:                   2            # user1 through user{{ openshift_user_count }}
openshift_user_password:                user#01

# install-config.yml variables
aws_region:                             eu-west-1
openshift_cluster_name:                 rsw-openshift
openshift_cluster_base_domain:          dt-redhat-workshop.com
openshift_cluster_fqdn:                 "{{ openshift_cluster_name }}.{{ openshift_cluster_base_domain }}"
openshift_control_node_instance_type:   m5a.xlarge     # default = 4vCPUs / 16 GB RAM (i.e. m5a.xlarge)
openshift_control_node_replicas:        3              # use a value of '3' only
openshift_worker_node_instance_type:    m5a.xlarge	   # default = 4vCPUs / 16 GB RAM (i.e. m5a.xlarge)
openshift_worker_node_replicas:         3              # default = '3'  Node counts of =< 3 are valid
openshift_install_pull_secret:          " {{ lookup('file', '{{ openshift_installer_path }}/pull-secret') }}"
openshift_node_ssh_public_key:          "{{ lookup('file', '{{ openshift_installer_path }}/{{ openshift_cluster_name }}-key.pub') }}"
openshift_installer_log_level:          debug          # recommended log level options: info or debug

# service mesh operator variables
elasticsearch_operator_version:         4.4
jaegar_operator_version:                stable
kiali_operator_version:                 stable
servicemesh_operator_version:           stable
keycloak_operator_version:              "v10.0.0"
